version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - .:/code
    command:
      - /bin/sh
      - -c
      - python manage.py migrate &&
        python manage.py collectstatic --no-input &&
        python manage.py makemessages && python manage.py compilemessages &&
        (python manage.py createsuperuser --no-input || true) &&
        python -m debugpy  --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data


networks:
  default:
    name: "template"

volumes:
  pgdata: {}
  s3data: {}